List the mapping predicates and abstract classes depending on the user session
learningtapestry/desm pull request #13
Opened 2021-11-12 21:34 UTC by richard0000

# Description
- From the session, take the user
- The user will determine the mapping predicates and abstract classes from the
configuration profile of its organization.

2021-11-13 14:44 UTC, excelsior requested changes

2021-11-13 14:44 UTC, excelsior commented on app/javascript/components/dashboard/configuration-profiles/ActivateProgress.jsx
> +            <Loader />
This component isn't imported here.

2021-11-15 14:14 UTC, richard0000 commented on app/javascript/components/dashboard/configuration-profiles/ActivateProgress.jsx
> +            <Loader />
@excelsior corrected.

2021-11-18 10:31 UTC, excelsior approved these changes

2021-11-18 17:09 UTC, merged